server:
  port: 80

logging:
  level:
    cn.blue: trace
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?serverTimezone=GMT%2b8
    username: root
    password: ly9781
mybatis:
  mapper-locations: classpath:cn/blue/mapper/sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
#  头像存储位置
head-img-path: classpath:/static/upload/heads